### ISSUE TITLE
Pdf file of Lecture 3 slides

### ISSUE THREAD

**Issue by mr-r0b0t** [HertieDataScience/SyllabusAndLectures#33]
Hi Christopher,

Could you please upload the pdf file of the slides of lecture 3 so that we can download the raw file?

Thank you very much!

Benedikt

**Comment by mcallaghan** [comment]
Hi Mr Robot,

I had a similar problem, but there is a way to view the html files straight away using https://rawgit.com/. it shows you how to append a file path to a html file on github so that you see it as a web page rather than the raw html. This makes lecture 3 available here:

https://cdn.rawgit.com/HertieDataScience/SyllabusAndLectures/master/LectureSlides/Lecture3/Lecture3.html

Hope this helps,

Max

**Comment by mr-r0b0t** [comment]
Hi Max,

I didn't know about rawgit, thanks a lot for the information! But it still does not allow me to download a pdf file that I can view and edit offline with another programme unfortunately...

Best,

Benedikt

**Comment by mcallaghan** [comment]
Hi Benedikt,

What you can do is open the file in a browser, or view it on rawgit, then click print, print to pdf, and change the page setup to landscape. This works ok for me in firefox, could be slightly different depending on browser or os

**Comment by mr-r0b0t** [comment]
You're right, that does work.

Thanks a lot for your quick help! :-)

Best,

Benedikt
